apiVersion: v1
kind: Namespace
metadata:
  name: poc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oidc-poc
  namespace: poc
  labels:
    app: oidc-poc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oidc-poc
    spec:
      containers:
      - name: oidc-poc
        image: ba2017/oidc-poc:v0.1
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:9000"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: oidc-poc
  namespace: poc
  labels:
    app: oidc-poc
spec:
  selector:
    app: oidc-poc
  ports:
  - port: 80
    targetPort: 9000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: oidc-poc
  namespace: poc
  labels:
    # let kube-cert-manager generate an SSL certificate
    stable.k8s.psg.io/kcm.class: "default"
spec:
  tls:
  - hosts:
    - oidc.zhaw.tk
    secretName: oidc-poc-tls-cert
  rules:
  - host: oidc.zhaw.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: oidc-poc
          servicePort: 80
